config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "trays#index"

  resources :trays do
    resources :cubes do
      resources :faces do
        collection do
          post :positions
        end
      end

      collection do
        post :positions
        delete :destroy_all, path: ""
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/strippable.rb
# frozen_string_literal: true

# Removes white space from model attributes.
module Strippable
  extend ActiveSupport::Concern

  # Allows attributes to be stripped.
  #   include Strippable
  #   strip :name, :description
  module ClassMethods
    def strip(*attributes)
      attributes.each do |attribute|
        class_eval <<-RUBY
          def #{attribute}=(attribute)
            super(attribute.try(:strip))
          end
        RUBY
      end
    end
  end
end

app/models/cube.rb
# frozen_string_literal: true

class Cube < ApplicationRecord
  # Constants
  CUBE_TYPES = [
    "section", "string", "choice", "number"
  ]

  # Concerns
  include Strippable
  strip :text, :description

  # Relationships
  belongs_to :tray
  has_many :faces, -> { order(:position) }, dependent: :destroy
end

app/models/face.rb
# frozen_string_literal: true

class Face < ApplicationRecord
  # Concerns
  include Strippable
  strip :text

  # Relationships
  belongs_to :cube
end

app/models/tray.rb
# frozen_string_literal: true

class Tray < ApplicationRecord
  # Concerns
  include Strippable
  strip :name

  # Relationships
  has_many :cubes, -> { order(:position) }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Protected methods

  protected

  def empty_response_or_root_path(path = root_path)
    respond_to do |format|
      format.html { redirect_to path }
      format.js { head :ok }
      format.json { head :no_content }
      format.pdf { redirect_to path }
    end
  end
end

app/controllers/cubes_controller.rb
# frozen_string_literal: true

class CubesController < ApplicationController
  before_action :find_tray_or_redirect
  before_action :find_cube_or_redirect, only: [:show, :edit, :update, :destroy]

  # GET /cubes
  # GET /cubes.json
  def index
    @cubes = @tray.cubes
  end

  # # GET /cubes/1
  # # GET /cubes/1.json
  # def show
  # end

  # GET /cubes/new
  def new
    @cube = @tray.cubes.new
  end

  # # GET /cubes/1/edit
  # def edit
  # end

  # POST /cubes
  # POST /cubes.json
  def create
    @cube = @tray.cubes.new(cube_params)
    respond_to do |format|
      if @cube.save
        format.html { redirect_to [@cube.tray, @cube], notice: "Cube was successfully created." }
        format.json { render :show, status: :created, location: [@tray, @cube] }
      else
        format.html { render :new }
        format.json { render json: @cube.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /cubes/1
  # PATCH /cubes/1.json
  def update
    respond_to do |format|
      if @cube.update(cube_params)
        format.html { redirect_to [@cube.tray, @cube], notice: "Cube was successfully updated." }
        format.json { render :show, status: :ok, location: [@tray, @cube] }
      else
        format.html { render :edit }
        format.json { render json: @cube.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /cubes/positions.json
  def positions
    @cubes = @tray.cubes.where(id: params[:cubes].keys)
    ActiveRecord::Base.transaction do
      @cubes.each do |cube|
        cube.update position: params[:cubes].dig(cube.id.to_s, :position)
      end
    end
    render :index
  end

  # DELETE /cubes/1
  # DELETE /cubes/1.json
  def destroy
    @cube.destroy
    respond_to do |format|
      format.html { redirect_to tray_cubes_url(@tray), notice: "Cube was successfully deleted." }
      format.json { head :no_content }
    end
  end

  # DELETE /trays/1/cubes
  def destroy_all
    @tray.cubes.destroy_all
    redirect_to @tray, notice: "Cubes were successfully deleted."
  end

  private

  def find_tray_or_redirect
    @tray = Tray.find_by(id: params[:tray_id])
    empty_response_or_root_path(trays_path) unless @tray
  end

  def find_cube_or_redirect
    @cube = @tray.cubes.find_by(id: params[:id])
    empty_response_or_root_path(@tray) unless @cube
  end

  def cube_params
    params.require(:cube).permit(:text, :description, :cube_type, :position)
  end
end

app/controllers/faces_controller.rb
class FacesController < ApplicationController
  before_action :find_tray_or_redirect
  before_action :find_cube_or_redirect
  before_action :find_face_or_redirect, only: [:show, :edit, :update, :destroy]

  # GET /faces
  # GET /faces.json
  def index
    @faces = @cube.faces
  end

  # # GET /faces/1
  # # GET /faces/1.json
  # def show
  # end

  # GET /faces/new
  def new
    @face = @cube.faces.new
  end

  # # GET /faces/1/edit
  # def edit
  # end

  # POST /faces
  # POST /faces.json
  def create
    @face = @cube.faces.new(face_params)
    respond_to do |format|
      if @face.save
        format.html { redirect_to [@face.cube.tray, @face.cube, @face], notice: "Face was successfully created." }
        format.json { render :show, status: :created, location: [@tray, @cube, @face] }
      else
        format.html { render :new }
        format.json { render json: @face.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /faces/1
  # PATCH /faces/1.json
  def update
    respond_to do |format|
      if @face.update(face_params)
        format.html { redirect_to [@face.cube.tray, @face.cube, @face], notice: "Face was successfully updated." }
        format.json { render :show, status: :ok, location: [@tray, @cube, @face] }
      else
        format.html { render :edit }
        format.json { render json: @face.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /faces/positions.json
  def positions
    @faces = @cube.faces.where(id: params[:faces].keys)
    ActiveRecord::Base.transaction do
      @faces.each do |face|
        face.update position: params[:faces].dig(face.id.to_s, :position)
      end
    end
    render :index
  end

  # DELETE /faces/1
  # DELETE /faces/1.json
  def destroy
    @face.destroy
    respond_to do |format|
      format.html { redirect_to tray_cube_faces_path(@face.cube.tray, @face.cube), notice: "Face was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def find_tray_or_redirect
    @tray = Tray.find_by(id: params[:tray_id])
    empty_response_or_root_path(trays_path) unless @tray
  end

  def find_cube_or_redirect
    @cube = @tray.cubes.find_by(id: params[:cube_id])
    empty_response_or_root_path(tray_cubes_path(@tray)) unless @cube
  end

  def find_face_or_redirect
    @face = @cube.faces.find_by(id: params[:id])
    empty_response_or_root_path([@tray, @cube]) unless @face
  end

  def face_params
    params.require(:face).permit(:position, :text)
  end
end

app/controllers/trays_controller.rb
# frozen_string_literal: true

class TraysController < ApplicationController
  before_action :set_tray, only: [:show, :edit, :update, :destroy]

  # GET /trays
  # GET /trays.json
  def index
    @trays = Tray.all
  end

  # # GET /trays/1
  # # GET /trays/1.json
  # def show
  # end

  # GET /trays/new
  def new
    @tray = Tray.new
  end

  # # GET /trays/1/edit
  # def edit
  # end

  # POST /trays
  # POST /trays.json
  def create
    @tray = Tray.new(tray_params)

    respond_to do |format|
      if @tray.save
        format.html { redirect_to @tray, notice: "Tray was successfully created." }
        format.json { render :show, status: :created, location: @tray }
      else
        format.html { render :new }
        format.json { render json: @tray.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /trays/1
  # PATCH /trays/1.json
  def update
    respond_to do |format|
      if @tray.update(tray_params)
        format.html { redirect_to @tray, notice: "Tray was successfully updated." }
        format.json { render :show, status: :ok, location: @tray }
      else
        format.html { render :edit }
        format.json { render json: @tray.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trays/1
  # DELETE /trays/1.json
  def destroy
    @tray.destroy
    respond_to do |format|
      format.html { redirect_to trays_url, notice: "Tray was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  def set_tray
    @tray = Tray.find(params[:id])
  end

  def tray_params
    params.require(:tray).permit(:name, :slug)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cubes/_form.html.haml
= form_with model: [cube.tray, cube], local: true do |form|
  - if cube.errors.any?
    #error_explanation
      %h2
        = pluralize(cube.errors.count, "error")
        prohibited this cube from being saved:

      %ul
        - cube.errors.full_messages.each do |message|
          %li= message

  .field
    = form.label :tray_id
    = form.number_field :tray_id

  .field
    = form.label :text
    = form.text_field :text

  .field
    = form.label :description
    = form.text_area :description

  .field
    = form.label :cube_type
    = form.select :cube_type, Cube::CUBE_TYPES

  .actions
    = form.submit

app/views/cubes/_wrapper.html.haml
- enter_question_placeholder = "Enter question here..."
.cube-wrapper{ class: cube.new_record? ? "cube-wrapper-unsaved" : nil, data: { object: "cube-wrapper", tray: cube.tray.to_param, cube: cube.id, url: tray_cubes_path(cube.tray), position: cube.position, position_original: cube.position, text_original: cube.text, cube_type: cube.cube_type.presence || "string" } }
  .cube
    = text_field_tag :cube, cube.text, placeholder: enter_question_placeholder, class: "cube-input", id: nil, autocomplete: "off"
    .cube-type
      %small= link_to cube.cube_type.presence || "string", "#", data: { object: "cube-details-clicker" }, tabindex: "-1"
    .cube-id
      %small= "##{cube.id.presence || "Ø"}"
      = cube.position.presence || "Ø"
  .cube-faces
    - cube.faces.includes(:cube).each do |face|
      = render "faces/wrapper", face: face
    - if !cube.new_record? && cube.faces.blank? && cube.cube_type == "choice"
      - face = cube.faces.new(position: 1)
      = render "faces/wrapper", face: face

app/views/cubes/edit.html.haml
%h1 Editing Cube

= render "form", cube: @cube

= link_to "Show", [@cube.tray, @cube]
|
= link_to "Back", tray_cubes_path(@tray)

app/views/cubes/index.html.haml
%h1 Cubes

%table.table.table-borderless.table-striped
  %thead
    %tr
      %th Position
      %th Text
      %th ID
      %th Cube type
      %th Tray
      %th.text-center{ colspan: 3 } Actions

  %tbody
    - @cubes.includes(:tray).each do |cube|
      %tr
        %td= cube.position
        %td= link_to cube.text.presence || cube.id, [cube.tray, cube]
        %td= cube.id
        %td= cube.cube_type
        %td= link_to cube.tray.name, cube.tray
        %td= link_to "Show", [cube.tray, cube]
        %td= link_to "Edit", edit_tray_cube_path(cube.tray, cube)
        %td= link_to "Destroy", [cube.tray, cube], method: :delete, data: { confirm: "Are you sure?" }

%br

= link_to "New Cube", new_tray_cube_path(@tray)

app/views/cubes/new.html.haml
%h1 New Cube

= render "form", cube: @cube

= link_to "Back", tray_cubes_path(@cube.tray)

app/views/cubes/show.html.haml
= link_to "Faces", [@cube.tray, @cube, :faces]

%p
  %strong Tray
  = @cube.tray_id

%p
  %strong Text
  = @cube.text

%p
  %strong Description
  = @cube.description

%p
  %strong Cube type
  = @cube.cube_type

= link_to "Edit", edit_tray_cube_path(@cube.tray, @cube)
|
= link_to "Back", tray_cubes_path(@tray)

app/views/faces/_form.html.haml
= form_with model: [face.cube.tray, face.cube, face], local: true do |form|
  .field
    = form.label :position
    = form.number_field :position

  .field
    = form.label :text
    = form.text_area :text

  .actions
    = form.submit

app/views/faces/_wrapper.html.haml
- enter_option_placeholder = "choice"
.face-wrapper{ class: face.new_record? ? "face-wrapper-unsaved" : nil, data: { object: "face-wrapper", cube: face.cube.to_param, face: face.id, url: tray_cube_faces_path(face.cube.tray, face.cube), position: face.position, position_original: face.position, text_original: face.text } }
  .face-prepend
    \-
  = text_field_tag :face, face.text, placeholder: enter_option_placeholder, class: "face-input", id: nil, autocomplete: "off"
  .face-id
    = face.position.presence || "Ø"

app/views/faces/edit.html.haml
%h1 Editing Face

= render "form", face: @face

= link_to "Show", [@face.cube.tray, @face.cube, @face]
|
= link_to "Back", [@face.cube.tray, @face.cube, :faces]

app/views/faces/index.html.haml
%h1
  .float-right= link_to "New Face", new_tray_cube_face_path(@tray, @cube), class: "btn btn-sm btn-primary"
  Faces

%table.table.table-borderless.table-striped
  %thead
    %tr
      %th Position
      %th Text
      %th Cube
      %th{ colspan: 3 }

  %tbody
    - @faces.includes(cube: :tray).each do |face|
      %tr
        %td= face.position
        %td= face.text
        %td= link_to face.cube.text, [face.cube.tray, face.cube]
        %td= link_to "Show", [face.cube.tray, face.cube, face]
        %td= link_to "Edit", edit_tray_cube_face_path(face.cube.tray, face.cube, face)
        %td= link_to "Destroy", [face.cube.tray, face.cube, face], method: :delete, data: { confirm: "Are you sure?" }

app/views/faces/new.html.haml
%h1 New Face

= render "form", face: @face

= link_to "Back", [@face.cube.tray, @face.cube, :faces]

app/views/faces/show.html.haml
%p
  %strong Cube
  = @face.cube_id

%p
  %strong Position
  = @face.position

%p
  %strong Text
  = @face.text

= link_to "Edit", edit_tray_cube_face_path(@face.cube.tray, @face.cube, @face)
|
= link_to "Back", [@face.cube.tray, @face.cube, :faces]

app/views/layouts/_flash_bar.html.haml
.flash-bar{ class: (flash[:notice].present? || flash[:alert].present? ? "flash-bar-show" : nil) }
  - if flash[:notice].present?
    = flash[:notice].html_safe
  - if flash[:alert].present?
    = flash[:alert].html_safe

app/views/layouts/_menu.html.haml
- menu = "menu-default" unless defined?(menu) && menu.present?
%nav.navbar.navbar-dark{ class: menu }
  .container
    = link_to root_path, class: "navbar-brand" do
      %i.fa.fa-cube
      Fridge

app/views/layouts/application.html.haml
!!!
%html{ lang: "en" }
  %head
    = render "layouts/head/title"
    = render "layouts/head/meta"
    = render "layouts/head/favicons"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", media: "all", data: { turbolinks_track: "reload" }
    = javascript_include_tag "application", data: { turbolinks_track: "reload" }
  - @random_theme ? render("themes/random") : render("themes/theme")
  %body#top.full-page.theme-bg{ class: @theme ? "theme-#{@theme}-bg" : nil, data: { theme: @theme } }
    = render "layouts/flash_bar"
    #top-menu.top-menu= render "layouts/menu", menu: @theme ? "menu-#{@theme}" : nil
    = yield :header
    .py-3
      .container= yield
    = yield :footer

app/views/layouts/head/_favicons.html.haml
= favicon_link_tag

app/views/layouts/head/_meta.html.haml
%meta{ charset: "utf-8" }
%meta{ content: "IE=Edge,chrome=1", http: { equiv: "X-UA-Compatible" } }
%meta{ name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no" }
%meta{ name: "description", content: "Project Fridge" }
%meta{ name: "author", content: "Remo Mueller" }
%meta{ name: "keywords", content: "fridge, freezer, sleep" }
-# Don't cache any pages
%meta{ name: "turbolinks-cache-control", content: "no-cache" }

app/views/layouts/head/_title.html.haml
%title= [@title, ENV["website_name"]].compact.join(" - ").html_safe

app/views/themes/_random.html.haml
- if params[:theme].present?
  - @theme = params[:theme]
- else
  -# @themes = Slice::THEMES.collect(&:second)
  - @theme = "default" # @themes[rand(@themes.size)]

app/views/themes/_theme.html.haml
- @theme = params[:theme].presence || "default"

app/views/trays/_form.html.erb
<%= form_with(model: tray, local: true) do |form| %>
  <% if tray.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tray.errors.count, "error") %> prohibited this tray from being saved:</h2>

      <ul>
      <% tray.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trays/edit.html.erb
<h1>Editing Tray</h1>

<%= render 'form', tray: @tray %>

<%= link_to 'Show', @tray %> |
<%= link_to 'Back', trays_path %>

app/views/trays/index.html.haml
%h1
  .float-right= link_to "New Tray", new_tray_path, class: "btn btn-sm btn-primary"
  Trays

%table.table.table-borderless.table-striped
  %thead
    %tr
      %th Name
      %th Slug
      %th{ colspan: 3 }
  %tbody
    - @trays.each do |tray|
      %tr
        %td= link_to tray.name, tray
        %td= tray.slug
        %td= link_to "Show", tray
        %td= link_to "Edit", edit_tray_path(tray)
        %td= link_to "Destroy", tray, method: :delete, data: { confirm: "Are you sure?" }

app/views/trays/new.html.erb
<h1>New Tray</h1>

<%= render 'form', tray: @tray %>

<%= link_to 'Back', trays_path %>

app/views/trays/show.html.haml
%h1
  .float-right= link_to "Destroy Cubes", tray_cubes_path(@tray), method: :delete, class: "btn btn-sm btn-danger"
  = @tray.name

%p
  = link_to "Edit", edit_tray_path(@tray)
  = link_to "Cubes", tray_cubes_path(@tray)
  = link_to "Back", trays_path


%p
  %strong Slug
  = @tray.slug

#output.text-monospace 0

- enter_question_placeholder = "Enter question here..."
- enter_option_placeholder = "choice"

%div.d-none#language{ data: { enter_question_placeholder: enter_question_placeholder, enter_option_placeholder: enter_option_placeholder } }

%hr

.d-flex.flex-row
  #cubes.w-100{ data: { object: "tray-wrapper" } }
    - @tray.cubes.includes(:tray).each do |cube|
      = render "cubes/wrapper", cube: cube

    - if @tray.cubes.blank?
      - cube = @tray.cubes.new(position: 1)
      = render "cubes/wrapper", cube: cube
  #cube-details-edit-box.w-25.cube-details-edit-box.d-none{ data: { url: tray_cubes_path(@tray) }}
    .float-right
      = link_to "#", data: { object: "cube-details-clicker-close" }, class: "text-muted", style: "text-decoration: none;" do
        &times;
    #cube-details-id Ø
    = form_with model: Cube.new, url: "#" do |form|
      .form-group
        = form.label :cube_type
        = form.select :cube_type, Cube::CUBE_TYPES, {}, class: "form-control"